const ROF=[
    {row:"Afghanistan"},
{row:"Algeria"},
{row:"Angola"},
{row:"Armenia"},
{row:"Azerbaijan"},
{row:"Bahrain"},
{row:"Bangladesh"},
{row:"Belarus"},
{row:"Benin"},
{row:"Bhutan"},
{row:"Bolivia"},
{row:"Botswana"},
{row:"Brunei"},
{row:"Burkina Faso"},
{row:"Burundi"},
{row:"Cambodia"},
{row:"Cameroon"},
{row:"Cape Verde"},
{row:"Central African Republic"},
{row:"Chad"},
{row:"China"},
{row:"Comoros"},
{row:"Democratic Republic of the Congo"},
{row:"Republic of the Congo"},
{row:"Costa Rica"},
{row:"Cote d'Ivoire"},
{row:"Cuba"},
{row:"Djibouti"},
{row:"Dominica"},
{row:"Dominican Republic"},
{row:"Ecuador"},
{row:"Egypt"},
{row:"El Salvador"},
{row:"Equatorial Guinea"},
{row:"Eritrea"},
{row:"Eswatini (formerly Swaziland)"},
{row:"Ethiopia"},
{row:"Fiji"},
{row:"Gabon"},
{row:"Gambia"},
{row:"Georgia"},
{row:"Ghana"},
{row:"Grenada"},
{row:"Guatemala"},
{row:Guinea},
{row:"Guinea-Bissau"},
{row:"Guyana"},
{row:"Haiti"},
{row:"Honduras"},
{row:"India"},
{row:"Indonesia"},
{row:"Iran"},
{row:"Iraq"},
{row:"Israel"},
{row:"Jamaica"},
{row:"Japan"},
{row:"Jordan"},
{row:"Kazakhstan"},
{row:"Kenya"},
{row:"Kiribati"},
{row:"Kuwait"},
{row:"Kyrgyzstan"},
{row:"Laos"},
{row:"Lebanon"},
{row:"Lesotho"},
{row:"Liberia"},
{row:"Libya"},
{row:"Madagascar"},
{row:"Malawi"},
{row:"Malaysia"},
{row:"Maldives"},
{row:"Mali"},
{row:"Marshall Islands"},
{row:"Mauritania"},
{row:"Mauritius"},
{row:"Mexico"},
{row:"Federated States of Micronesia"},
{row:"Moldova"},
{row:"Mongolia"},
{row:"Montenegro"},
{row:"Morocco"},
{row:"Mozambique"},
{row:"Myanmar (formerly Burma)"},
{row:"Namibia"},
{row:"Nauru"},
{row:"Nepal"},
{row:"New Zealand"},
{row:"Nicaragua"},
{row:"Niger"},
{row:"Nigeria"},
{row:"North Korea"},
{row:"North Macedonia (formerly Macedonia)"},
{row:"Oman"},
{row:"Pakistan"},
{row:"Palau"},
{row:"Panama"},
{row:"Papua New Guinea"},
{row:"Paraguay"},
{row:"Peru"},
{row:"Philippines"},
{row:"Qatar"},
{row:"Russia"},
{row:"Rwanda"},
{row:"Saint Kitts and Nevis"},
{row:"Saint Lucia"},
{row:"Saint Vincent and the Grenadines"},
{row:"Samoa"},
{row:"Sao Tome and Principe"},
{row:"Saudi Arabia"},
{row:"Senegal"},
{row:"Serbia"},
{row:"Seychelles"},
{row:"Sierra Leone"},
{row:"Singapore"},
{row:"Solomon Islands"},
{row:"Somalia"},
{row:"South Africa"},
{row:"South Korea"},
{row:"South Sudan"},
{row:"Sri Lanka"},
{row:"Sudan"},
{row:"Suriname"},
{row:"Syria"},
{row:"Taiwan"},
{row:"Tajikistan"},
{row:"Tanzania"},
{row:"Thailand"},
{row:"Timor-Leste (formerly East Timor)"},
{row:"Togo"},
{row:"Tonga"},
{row:"Trinidad and Tobago"},
{row:"Tunisia"},
{row:"Turkey"},
{row:"Turkmenistan"},
{row:"Tuvalu"},
{row:"Uganda"},
{row:"Ukraine"},
{row:"United Arab Emirates"},
{row:"Uzbekistan"},
{row:"Vanuatu"},
{row:"Venezuela"},
{row:"Vietnam"},
{row:"Yemen"},
{row:"Zambia"},
{row:"Zimbabwe"},

]
